fixtures:
  repositories:
    facts:
      repo: "git://github.com/donoghuc/puppetlabs-facts"
      branch: "modules-9530"
  symlinks:
    puppet_agent: "#{File.absolute_path(File.join(source_dir, '..'))}"
